### ISSUE TITLE
Failed to activate the linter-clang package

### ISSUE THREAD

**Issue by jamiltron** [AtomLinter/linter-clang#185]
Steps to reproduce:

1. Open Atom

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [linter-clang](https://github.com/AtomLinter/linter-clang) package 3.4.8

### Stack Trace

Failed to activate the linter-clang package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Object.activate (/packages/linter-clang/lib/main.js:54:5)
  at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
  at /app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at /app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
  at /app.asar/src/package-manager.js:531:29
  at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
  at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
  at /app.asar/src/atom-environment.js:814:28

```

### Commands

```
     -0:09.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
arduino-toolbelt 0.1.1 
arduino-upload 1.0.3 
atom-beautify 0.29.17 
atom-typescript 10.1.14 
atom-yeoman 0.3.15 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-clang 0.10.0 
autocomplete-glsl 0.2.3 
autocomplete-go 1.3.0 
autocomplete-haskell 0.7.2 
autocomplete-love 0.3.0 
build-cargo 2.0.0 
build-cmake 0.8.3 
build-tools 4.5.7 
build-tools-make 0.2.1 
builder-go 1.0.1 
cargo-test-runner 0.1.0 
clang-format 1.28.0 
comment-dwim-light 0.9.6 
cpp-generator 0.1.0 
elm-format 2.1.0 
emacs-plus 0.11.1 
file-icons 2.0.15 
gcc-make-run 0.2.9 
git-control 0.8.2 
git-projects 1.17.0 
go-config 1.2.4 
go-debug 1.0.4 
go-get 2.1.1 
go-plus undefined 
godoc 1.1.1 
gofmt 1.2.0 
gometalinter-linter 1.2.2 
gorename 1.1.0 
haskell-ghc-mod 1.19.7 
haskell-hoogle 0.1.3 
haskell-pointfree 0.1.4 
haskell-unicode-snippets 0.1.1 
haxe 0.8.14 
haxe-import 1.2.1 
highlight-selected 0.12.0 
hyperclick 0.0.40 
hyperclick-love 0.4.0 
ide-haskell 1.9.4 
ide-haskell-cabal 1.8.0 
ide-haskell-hasktags 0.0.10 
ide-haskell-repl 0.5.2 
json-schema 0.1.15 
language-arduino 0.4.2 
language-cpp14 0.6.2 
language-elm 1.5.0 
language-glsl 2.0.1 
language-haskell 1.12.1 
language-haxe 0.5.4 
language-lua 0.9.11 
language-moonscript 1.7.1 
language-ocaml 1.1.2 
language-racket 0.4.0 
language-rust 0.4.9 
language-scala 1.1.8 
language-sml 0.7.0 
language-valgrind 0.1.0 
linter 1.11.23 
linter-clang 3.4.8 
linter-cpplint 1.0.1 
linter-elm-make 0.22.5 
linter-emscripten 0.1.1 
linter-glsl 2.1.1 
linter-hlint 0.5.0 
linter-js-yaml 1.2.7 
linter-lua 1.0.2 
linter-luaparse 0.2.0 
linter-markdown 3.1.0 
linter-moonscript 1.1.1 
linter-rust 0.7.2 
love-ide 0.14.0 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.1 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
monokai-seti 0.7.0 
navigator-go 1.1.3 
nim 0.3.6 
omnisharp-atom 0.31.1 
open-recent 5.0.0 
pigments 0.39.0 
project-manager 3.3.3 
racer 0.20.0 
rust-api-docs-helper 0.5.1 
rustfmt 0.1.3 
script 3.14.1 
seti-ui 1.6.1 
solarized-seti-ui 0.8.6 
switch-header-source 0.22.0 
tester-go 2.0.2 
todo-show 1.11.0 
tool-bar 1.0.1 
tool-bar-almighty 0.8.1 
yaml-sortkey 0.1.0 
```

**Comment by Arcanemagus** [comment]
Can you please try re-installing the package? It seems like APM has failed to install all the dependencies properly.

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response, if you are still having problems feel free to comment further!
