### ISSUE TITLE
Uncaught TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by h-rodz10** [AtomLinter/linter-clang#29]
Trying to type anything in C/C++ gives a big red error box. 

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-clang](https://github.com/AtomLinter/linter-clang) package, v2.17.0

### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:333

TypeError: Arguments to path.resolve must be strings
  at Object.exports.resolve (path.js:333:15)
  at LinterClang.lintFile (/Users/Abdiel/.atom/packages/linter-clang/lib/linter-clang.coffee:73:21)
  at /Users/Abdiel/.atom/packages/linter/lib/linter-view.coffee:139:18
  at Array.forEach (native)
  at /Users/Abdiel/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -4:25.6 grammar-selector:show (atom-text-editor.editor.is-focused)
     -4:08.2 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
  3x -3:57.8 grammar-selector:show (atom-text-editor.editor.is-focused)
  6x -3:18.5 core:backspace (atom-text-editor.editor.is-focused)
     -3:15.5 autocomplete:toggle (atom-text-editor.editor.is-focused)
  3x -3:01.6 grammar-selector:show (atom-text-editor.editor.is-focused)
     -2:24.8 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:40.4 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:05.2 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.10.0
linter-clang, v2.17.0
linter-csslint, v0.0.11
linter-htmlhint, v0.0.8
linter-jshint, v0.1.0
linter-php, v0.0.11
minimap, v3.5.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by h-rodz10** [comment]
Release 2.19.0 and a complete reinstall of OS X Command Line Tools fixed the issue on my machine.
