### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/.DocumentRevisions-V100'

### ISSUE THREAD

**Issue by rohan07** [AtomLinter/linter-clang#35]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter-clang](https://github.com/AtomLinter/linter-clang) package, v2.19.0

### Stack Trace

Uncaught Error: EACCES, permission denied '/.DocumentRevisions-V100'

```
At fs.js:691

Error: EACCES, permission denied '/.DocumentRevisions-V100'
  at Error (native)
  at Object.fs.readdirSync (fs.js:691:18)
  at Object.fs.readdirSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:398:26)
  at searchDirectory (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:91:17)
  at searchDirectory (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:95:11)
  at LinterClang.lintFile (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:101:5)
  at /Users/Rohan/.atom/packages/linter/lib/linter-view.coffee:139:18
  at Array.forEach (native)
  at /Users/Rohan/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -0:28.2 editor:newline (input.hidden-input)
     -0:27.7 snippets:next-tab-stop (input.hidden-input)
     -0:27.7 snippets:expand (input.hidden-input)
     -0:27.7 editor:indent (input.hidden-input)
     -0:19.2 snippets:next-tab-stop (input)
     -0:19.2 snippets:expand (input)
     -0:18.2 core:undo (input.hidden-input)
     -0:17.1 core:move-right (input.hidden-input)
     -0:16.1 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:16.1 editor:newline (input.hidden-input)
  8x -0:15.4 core:backspace (input.hidden-input)
     -0:13.1 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:13.1 editor:newline (input.hidden-input)
 10x -0:04.7 core:backspace (input.hidden-input)
     -0:01.1 grammar-selector:show (atom-text-editor.editor.editor-colors.vim-mode.insert-mode)
     -0:00.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "atom-lint"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v1.5.0
autoclose-html, v0.14.0
autocomplete-clang, v0.6.1
autocomplete-plus, v1.1.0
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v0.3.2
color-picker, v1.4.4
emmet, v2.3.2
file-icons, v1.4.8
git-tab-status, v1.5.2
highlight-line, v0.9.3
javascript-snippets, v1.0.0
jshint, v1.2.0
linter, v0.10.1
linter-clang, v2.19.0
linter-cpplint, v0.1.3
linter-csslint, v0.0.11
linter-flake8, v1.2.0
linter-htmlhint, v0.0.8
linter-javac, v0.1.3
linter-jshint, v0.1.0
linter-jsxhint, v0.1.0
linter-pylama, v0.0.15
linter-pylint, v0.2.0
meteor-api, v2.9.0
minimap, v3.5.6
monokai, v0.11.0
project-manager, v1.15.0
react, v0.9.3
save-session, v0.11.3
script, v2.16.0
terminal-status, v1.3.5
travis-ci-status, v0.11.1
vim-mode, v0.29.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by m-bra** [comment]
Simple as that: you can't open /.DocumentRevisions-V100 because you do not have the rights (if I understood the problem). Did you open the file by yourself or did atom do it?

**Comment by rohan07** [comment]
I opened it myself.

**Comment by m-bra** [comment]
Can you open the file with any other text editor? If not, then it is not related to atom. However, to gain the rights of the file, you can copy it to a location you can read and write to (like desktop) or start atom with administrative rights or just don't edit it within atom. What do you want to do with the file?

**Comment by k2b6s9j** [comment]
Please run the command `ls -l` in the directory containing this file and copy the line containing the file name.

**Comment by m-bra** [comment]
This is likely a bug solved by #45 . Please respond if not solved or close the issue if the bug has been fixed.

**Comment by m-bra** [comment]
The file has not been opened by you but by the linter itself; it searches your directory for ".linter-clang-includes" and checks every file. If the file cant be opened, however, the linter *used to* crash. This has been fixed. _(Look at the stack trace: the `searchDirectory` function does that)_

**Comment by k2b6s9j** [comment]
Are you still having this issue?

**Comment by k2b6s9j** [comment]
@rohan07 Are you still having this issue?

**Comment by rohan07** [comment]
Nope, solved it.
