### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by aaronpuchert** [AtomLinter/linter-clang#44]
Symbolic links to non-existent files in a repository cause the clang-linter to throw an exception, when it traverses the tree to look for `#include <>`s. Though I'm not sure if this isn't a bug in the atom core.

**Atom Version**: 0.172.0
**System**: linux 3.18.3-1-desktop
**Thrown From**: [linter-clang](https://github.com/AtomLinter/linter-clang) package, v2.22.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/aaron/src/[radare2/prefix/bin/rabin2](https://github.com/radare/radare2/blob/master/prefix/bin/rabin2)'

```
At /usr/local/share/atom/resources/atom/common/lib/asar.js:52

Error: ENOENT, no such file or directory '[...]'
  at Error (native)
  at fs.statSync (fs.js:726:18)
  at Object.fs.statSync (/usr/local/share/atom/resources/atom/common/lib/asar.js:155:14)
  at searchDirectory (/home/aaron/.atom/packages/linter-clang/lib/linter-clang.coffee:94:19)
  at searchDirectory (/home/aaron/.atom/packages/linter-clang/lib/linter-clang.coffee:96:11)
  at searchDirectory (/home/aaron/.atom/packages/linter-clang/lib/linter-clang.coffee:96:11)
  at LinterClang.lintFile (/home/aaron/.atom/packages/linter-clang/lib/linter-clang.coffee:120:5)
  at /home/aaron/.atom/packages/linter/lib/linter-view.coffee:139:18
  at Array.forEach (native)
  at /home/aaron/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Object.oncomplete (fs.js:93:15)

```

/cc @atom/core

**Comment by m-bra** [comment]
This is a bug. While searching, the linter has to take file errors into account. Will fix that.
