### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/Rohan/.Trash/LaTeXiT (2.6.1).app/Contents/Frameworks/LinkBack.framework/Headers/Headers'

### ISSUE THREAD

**Issue by rohan07** [AtomLinter/linter-clang#47]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter-clang](https://github.com/AtomLinter/linter-clang) package, v2.22.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/Rohan/.Trash/LaTeXiT (2.6.1).app/Contents/Frameworks/LinkBack.framework/Headers/Headers'

```
At fs.js:726

Error: ENOENT, no such file or directory '/Users/Rohan/.Trash/LaTeXiT (2.6.1).app/Contents/Frameworks/LinkBack.framework/Headers/Headers'
  at Error (native)
  at fs.statSync (fs.js:726:18)
  at Object.fs.statSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:155:14)
  at searchDirectory (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:94:19)
  at searchDirectory (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:96:11)
  at searchDirectory (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:96:11)
  at searchDirectory (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:96:11)
  at searchDirectory (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:96:11)
  at searchDirectory (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:96:11)
  at searchDirectory (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:96:11)
  at LinterClang.lintFile (/Users/Rohan/.atom/packages/linter-clang/lib/linter-clang.coffee:120:5)
  at /Users/Rohan/.atom/packages/linter/lib/linter-view.coffee:139:18
  at Array.forEach (native)
  at /Users/Rohan/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "deprecation-cop"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "audioBeep": false
  },
  "linter-clang": {
    "clangCompleteFile": true,
    "clangSuppressWarnings": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v1.5.0
atom-lint, v0.20.1
autoclose-html, v0.14.0
autocomplete-clang, v0.6.1
autocomplete-plus, v2.0.3
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v1.0.0
color-picker, v1.4.4
emmet, v2.3.2
file-icons, v1.4.8
git-log, v0.2.0
git-tab-status, v1.5.3
highlight-line, v0.9.3
javascript-snippets, v1.0.0
jshint, v1.2.0
jsonlint, v1.0.0
language-latex, v0.4.1
latex, v0.16.0
linter, v0.10.1
linter-clang, v2.22.0
linter-cpplint, v0.1.3
linter-csslint, v0.0.11
linter-flake8, v1.2.0
linter-htmlhint, v0.0.8
linter-javac, v0.1.3
linter-jshint, v0.1.0
linter-jsonlint, v0.1.2
linter-jsxhint, v0.1.0
linter-pylama, v0.0.15
linter-pylint, v0.2.0
markdown-preview-plus, v1.1.0
mathjax-wrapper, v0.1.0
meteor-api, v2.9.0
minimap, v3.5.6
monokai, v0.12.0
pdf-view, v0.15.0
project-manager, v1.15.5
react, v0.9.7
save-session, v0.11.3
script, v2.16.0
terminal-status, v1.3.5
travis-ci-status, v0.11.2
vim-mode, v0.30.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by m-bra** [comment]
Already fixed with merged PR #45 . Build this package manually or wait for update.
